# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calibration(object):
    def setupUi(self, Calibration):
        Calibration.setObjectName("Calibration")
        Calibration.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Calibration)
        self.centralwidget.setObjectName("centralwidget")
        self.Calibrate = QtWidgets.QPushButton(self.centralwidget)
        self.Calibrate.setGeometry(QtCore.QRect(270, 420, 201, 101))
        self.Calibrate.setObjectName("Calibrate")
        Calibration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calibration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Calibration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calibration)
        self.statusbar.setObjectName("statusbar")
        Calibration.setStatusBar(self.statusbar)

        self.retranslateUi(Calibration)
        QtCore.QMetaObject.connectSlotsByName(Calibration)

    def retranslateUi(self, Calibration):
        _translate = QtCore.QCoreApplication.translate
        Calibration.setWindowTitle(_translate("Calibration", "MainWindow"))
        self.Calibrate.setText(_translate("Calibration", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calibration = QtWidgets.QMainWindow()
    ui = Ui_Calibration()
    ui.setupUi(Calibration)
    Calibration.show()
    sys.exit(app.exec_())
